version: '3.8'

services:
  mqtt-emulator:
    build: ./emulators/mqtt
    container_name: mqtt-honeypot
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/honeypot
    restart: always

  ssh-emulator:
    build: ./emulators/ssh
    container_name: ssh-honeypot
    ports:
      - "5001:5001"
      - "2222:2222"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/honeypot
    restart: always

  fake-router:
    build: ./emulators/fake-router
    container_name: fake-router
    ports:
      - "5003:5003"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/honeypot
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: honeypot-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
